### Create a new user
POST http://localhost:3000/auth/signup
content-type: application/json

{
  "email": "test@test.com",
  "password": "12345"
}

### Sign in as an existing user
POST http://localhost:3000/auth/signin
content-type: application/json

{
  "email": "test@test.com",
  "password": "12345"
}

### Get the currently signed in user
GET http://localhost:3000/auth/whoami

### Sign out
POST http://localhost:3000/auth/signout

### Find a particular user with a given ID
GET http://localhost:3000/auth/2

### Find all users with a given email
GET http://localhost:3000/auth?email:asdf@asdf.com

### Delete a user with a given id
DELETE http://localhost:3000/auth/1

### Update a user
PATCH http://localhost:3000/auth/2
content-type: application/json

{
  "email": "aaaaa@aaaaa.com"
}

### Set a color
Get http://localhost:3000/auth/colors/red

### Get the color
GET http://localhost:3000/auth/colors

POST http://localhost:3000/reports
content-type: application/json

{
  "make": "toyota",
  "model": "corolla",
  "year": 1980,
  "mileage": 100000,
  "lng": 0,
  "lat": 0,
  "price": 500000
}